### ISSUE TITLE
sysbench crashes under supermalloc

### ISSUE THREAD

**Issue by kuszmaul** [kuszmaul/SuperMalloc#33]
On 12/15/14:

Reported by prohaska:

crash @
#0  0x00007ffff7413504 in try_put_cached (obj=0x8000c4000980, co=0x7ffff7f6cac0, size=8, cache_size=8192) at ../src/cache.cc:557

#1  0x00007ffff741358f in try_put_cached_both (obj=0x8000c4000980, cb=0x7ffff7f6cac0, size=8, cache_size=8192) at ../src/cache.cc:578

#2  0x00007ffff7413d99 in cached_free (ptr=0x8000c4000980, bin=0) at ../src/cache.cc:768

#3  0x00007ffff740b64b in free (p=0x7fffc4000980) at ../src/malloc.cc:257

how to reproduce:

step 1: build a debug environment

mkdir percona-supermalloc

cd percona-supermalloc

bash -x ~/make.bash

step 2: run mysqld with supermalloc and tokudb

cd install

gdb bin/mysqld

gdb> set environment LD_PRELOAD=SOME_PATH/libsupermalloc_pthread.so

gdb> run --defaults-file=~/rfp.cnf --gdb --plugin-load=tokudb=ha_tokudb.so

step 3: make sure that supermalloc is loaded into mysqld

step 4: get ready for sysbench

mysql -S/tmp/rfp.sock -uroot

mysql> show engines; # make sure that tokudb is running

mysql> grant all on *.* to rfp@localhost;

mysql> create database sbtest

step 5: use sysbench to prepare the tables

sysbench --test=$HOME/launchpad/sysbench/sysbench/tests/db/oltp.lua --mysql-user=rfp --mysql-table-engine=tokudb --oltp-tables-count=8 --oltp-table-size=1000000 --mysql-socket=/tmp/rfp.sock prepare

this should create 8 tables with 1M rows each.  it is failing on my machine after a couple of tables are built.

**Comment by kuszmaul** [comment]
Fixed as of 2/11/15 see github.mit.edu
